const hospitalImages = {
  "Apollo Cancer Centre Visakhapatnam": "apollo.jpeg",
  "Apollo Cancer Centre Vijayawada": "apollo.jpeg",
  "Apollo Specialty Hospital Tirupati Oncology": "tirupati.jpeg",
  "Homi Bhabha Cancer Hospital & Research Centre": "homi.jpeg",
  "HCG Pinnacle Oncology Centre": "hcg.jpeg",
  "King George Hospital Cancer Unit": "kgh.jpeg",
  "Lions Cancer Treatment & Research Centre": "lion.jpeg",
  "American Oncology Institute Vijayawada": "american.jpeg",
  "Nagarjuna Cancer Centre": "naga.jpeg",
  "Dr Y V Rao Cancer Centre": "yvrao.jpeg",
  "Ravis American Cancer Care": "ravi.jpeg",
  "NRI Medical College & General Hospital Oncology Department": "nri.jpeg",
  "Government General Hospital Guntur Oncology": "ggh.jpeg",
  "Ramesh Hospitals Oncology Unit": "ramesh.jpeg",
  "Helios Hospitals Oncology": "helios.jpeg",
  "Kurnool Institute of Oncology":"Kurnool Institute of Oncology.jpg",
  "KIMS Hospital Kurnool Oncology":"KIMS Hospital Kurnool Oncology.jpg",
  "Omega Hospitals Kurnool Oncology Unit":"Omega Hospitals Kurnool Oncology Unit.jpg",
  "Ramakrishna Mission Hospital":"ramakrishna mission hospital, Itanagar.jpg",
  "Tomo Riba Institute of Health and Medical Sciences": "tomo riba institute itanagar.jpg",
  "Arunachal State Hospital":"arunachal state hospital.jpg",
  "Bakin Pertin General Hospital":"Bakin pertin.jpg",
  "District Hospital Tawang":"distric hospital tawang.jpg",
  "Gyati Takka General Hospital":"Gyati Takka General Hospital, Ziro.jpg",
  "Tata Memorial Hospital":"Tata Memorial Hospital.jpg",
"Kokilaben Dhirubhai Ambani Hospital and Medical Research Institute":"Kokilaben Dhirubhai Ambani Hospital and Medical Research Institute.jpg",
"Nanavati Max Super Speciality Hospital Mumbai":"Nanavati Max Super Speciality Hospital Mumbai.jpg",
"Jaslok Hospital & Research Centre":"Jaslok Hospital & Research Centre.jpg",
"HCG ICS Khubchandani Cancer Hospital":"HCG ICS Khubchandani Cancer Hospital.jpg",
"Ruby Hall Clinic":"Ruby Hall Clinic.jpg",
"TGH Onco Life Cancer Centre, Talegaon Dabhade":"TGH Onco Life Cancer Centre, Talegaon Dabhade.jpg",
"Deenanath Mangeshkar Hospital":"Deenanath Mangeshkar Hospital.jpg",
"Sahyadri Hospitals":"Sahyadri Hospitals.jpg",
"Aditya Birla Memorial Hospital":"Aditya Birla Memorial Hospital.jpg",
"Galaxy Care Hospital":"Galaxy Care Hospital.jpg",
"National Cancer Institute":"National Cancer Institute, nagpur.jpg",
"Max Super Speciality Hospital":"Max Super Speciality Hospital.jpg",
"Kingsway Hospitals":"Kingsway Hospitals.jpg",
"Wockhardt Hospitals Nagpur":"Wockhardt Hospitals Nagpur.jpg",
"Orange City Hospital and Research Institute":"Orange City Hospital and Research Institute.jpg",
"HCG Manavata Cancer Centre":"HCG Manavata Cancer Centre.jpg",
"Curie Manavata Cancer Centre":"Curie Manavata Cancer Centre.jpg",
"Wockhardt Hospitals Nashik":"Wockhardt Hospitals Nashik.jpg",
"Apollo Hospitals Nashik":"Apollo Hospitals Nashik.jpg",
"Six Sigma Hospitals":"Six Sigma Hospitals.jpg",
"Kolhapur Cancer Centre":"Kolhapur Cancer Centre.jpg",
"Aster Aadhar Hospital":"Aster Aadhar Hospital.jpg",
"Krishna Hospital Kolhapur":"krishna hospital kolhapur.jpg",
"Apple Saraswati Multispeciality Hospital":"Apple Saraswati Multispeciality Hospital.jpg",
"Chaitanya Cancer Hospital":"Chaitanya Cancer Hospital.jpg",
"KIMS Hospital Kurnool Oncology":"KIMS Hospital Kurnool Oncology.jpg",
"Kurnool Institute of Oncology":"Kurnool Institute of Oncology.jpg",
"Omega Hospitals Kurnool Oncology Unit":"Omega Hospitals Kurnool Oncology Unit.jpg",
"Ramakrishna Mission Hospital":"ramakrishna mission hospital, Itanagar.jpg",
"Tomo Riba Institute of Health and Medical Sciences":"tomo riba institute itanagar.jpg",
"Arunachal State Hospital":"arunachal state hospital.jpg",
"Bakin Pertin General Hospital":"Bakin pertin.jpg",
"District Hospital Tawang":"distric hospital tawang.jpg",
"Gyati Takka General Hospital":"Gyati Takka General Hospital, Ziro.jpg",

};

export default hospitalImages;